production:
  address: "smtp1.s.ipzmarketing.com" # Your SMTP server address
  port: "587" # Port 465 for SSL
  enable_starttls_auto: true # Disable TLS
  user_name: "nqgkdgvqyxme"
  password: "geeNcptXJxI"
  authentication: "plain" # secure authentication plain, login, or cram_md5
  domain: "paisdelconocimiento.org" # Your SMTP server address
  outgoing_address: "juan.villa@paisdelconocimiento.org"
  default_name: "Academia Pais del Conocimiento"
# or to use sendmail .
#
# development:
#   delivery_method: "sendmail"

test:
  delivery_method: "test"
  
development:
  address: "smtp1.s.ipzmarketing.com" # Your SMTP server address
  port: "587" # Port 465 for SSL
  enable_starttls_auto: true # Disable TLS
  ssl: true # Enable SSL
  user_name: "nqgkdgvqyxme"
  password: "geeNcptXJxI"
  authentication: "login" # secure authentication plain, login, or cram_md5
  domain: "smtp1.s.ipzmarketing.com" # Your SMTP server address
  outgoing_address: "juan.villa@paisdelconocimiento.org"
  default_name: "Universidad en Linea"
# If receiving mail from multiple inboxes (see incoming_mail.yml.example),
# you'll want to include those addresses in a reply_to_addresses array so
# Canvas will select the Reply-To field of outgoing messages from all of the
# incoming mailboxes.

multiple_inboxes:
  address: "smtp.example.com"
  port: "25"
  user_name: "user"
  password: "password"
  authentication: "plain" # plain, login, or cram_md5
  domain: "example.com"
  outgoing_address: "canvas@example.com"
  default_name: "Instructure Canvas"
  reply_to_addresses:
  - "canvas1@example.com"
  - "canvas2@example.com"
  - "canvas3@example.com"
  - "canvas4@example.com"
