bash
cd /var/cd/
RAILS_ENV=production bundle exec rake db:initial_setup
mv db/migrate/20210823222355_change_immersive_reader_allowed_on_to_on.rb .
mv db/migrate/20210812210129_add_singleton_column.rb db/migrate/20111111214311_add_singleton_column.rb
RAILS_ENV=production bundle exec rake db:initial_setup
mv 20210823222355_change_immersive_reader_allowed_on_to_on.rb db/migrate/.
RAILS_ENV=production bundle exec rake db:migrate
mv 20210823222355_change_immersive_reader_allowe
RAILS_ENV=production bundle exec rake db:migrate
unset CANVAS_LMS_ADMIN_EMAIL CANVAS_LMS_ADMIN_PASSWORD CANVAS_LMS_ACCOUNT_NAME CANVAS_LMS_STATS_COLLECTION
mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands
touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss
touch Gemfile.lock
touch log/production.log
sudo chown -R $USER config/environment.rb log tmp public/assets \
                              app/stylesheets/_brandable_variables_defaults_autogenerated.scss \
                              app/stylesheets/brandable_css_brands Gemfile.lock config.ru
RAILS_ENV=production bundle exec rake canvas:compile_assets
chown -R $USER public/dist/brandable_css
