sudo npm -g install yarn
yarn install --verbose
cd /var/canvas
yarn gulp rev
RAILS_ENV=production bundle exec rake db:initial_setup
mv db/migrate/20210823222355_change_immersive_reader_allowed_on_to_on.rb .
mv db/migrate/20210812210129_add_singleton_column.rb db/migrate/20111111214311_add_singleton_column.rb
yarn gulp rev
RAILS_ENV=production bundle exec rake db:initial_setup
mv 20210823222355_change_immersive_reader_allowed_on_to_on.rb db/migrate/.
RAILS_ENV=production bundle exec rake db:migrate
cd /var/canvas
mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands
touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss
touch Gemfile.lock
touch log/production.log
sudo chown -R canvas config/environment.rb log tmp public/assets \
                                  app/stylesheets/_brandable_variables_defaults_autogenerated.scss \
                                  app/stylesheets/brandable_css_brands Gemfile.lock config.ru
